FROM cgr.dev/chainguard/wolfi-base

# Install dev tools
RUN apk add --no-cache curl bash git build-base ca-certificates libudev pkgconf

# Install Rust and Solana
RUN set -euxo pipefail && \
    curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain 1.73.0

ENV PATH="/root/.cargo/bin:$PATH"

RUN set -euxo pipefail && \
    curl -sSfL https://release.anza.xyz/stable/install -o /tmp/install.sh && \
    sh /tmp/install.sh

ENV PATH="/root/.local/share/solana/install/active_release/bin:$PATH"

# Verify
# RUN solana --version && cargo --version